### PR TITLE
Use ABSOLUTE_URL constant on URL generation, closes #345

### LINKED ISSUE #345: Generate URL should use ABSOLUTE_URL not ABSOLUTE_PATH
See https://github.com/messagedigital/cog/blob/186159a0bbafb32c80584b3a58cdca8d5de6a7f1/src/Controller/Controller.php#L134

This means the url generated is actually just `/foo/bar` instead of `http://example.org/foo/bar`.

If changed to use `UrlGeneratorInterface::ABSOLUTE_URL` it works as expected.

Unless this is the expected behavour?

### PR DESCRIPTION
**Pull request by thomasjthomasj**
This PR resolves issue #345.

To test this I checked that the following worked:

+ Links on front end
+ Links in admin panel
+ Links sent to flash messages (e.g. when deleting a page or change a flash message to one from a deleted page)
+ Submitting forms with an action set

### CODE REVIEW

**Comment by kuiche** [comment]
Is this actually a bug? They both work equally fine. I was looking at that issue yesterday and considered straight up just closing it.

**Comment by thomasjthomasj** [comment]
Well my feeling is that while they both work the ABSOLUTE_URL one at least seems more semantically correct

**Comment by kuiche** [comment]
I don't think it's any more semantically correct. Absolute paths are for site internal links. The links generated the site are for the site so straight up absolute path makes perfect sense. I don't really think it matters either way.

**Comment by kuiche** [comment]
It also makes the links generated inconsistent with Slug links i.e. any CMS page link.

**Pull request closed without merging**
