### PR TITLE
Update Bcrypt.php

### PR DESCRIPTION
**Pull request by sarciszewski**
Incorporate some of the changes from https://github.com/ircmaxell/password_compat

### CODE REVIEW

**Comment by thomasjthomasj** [comment]
Hi Scott

Welcome to Mothership, and that's a lot for these contributions. I've taken a look at this one and aside from these minor code-style comments it all looks good to me

Make these changes and I'm happy to merge it :)

**Comment by sarciszewski** [comment]
Sure thing. That was copypasta from password_compat. I've pushed another commit to the branch.

**Comment by kuiche** [comment]
Another minor code comment - the stuff you've copied uses spaces. We prefer tabs, more importantly the file is now a mixture of spaces and tabs for indentation.

**Comment by thomasjthomasj** [comment]
Nice catch Sam

As a side note, we should probably publish a page on Mothership code guidelines on the wiki

**Comment by sarciszewski** [comment]
Crap, I'm using Github's online editor. I don't have a tab-friendly IDE on this device (I use PSR-2 for everything where I can). It might be quicker if you guys recreate the changes separately in a manner consistent with your coding style.

**Comment by thomasjthomasj** [comment]
No worries Scott, will do

**Pull request closed without merging**
